### PR TITLE
Enable container image build

### PR DESCRIPTION
**Pull request by krishvoor**
Enable container image build -

1) Enables TravisCI
2) Creates/ Publishes container image build
3) Creates/ Publishes manifests

### CODE REVIEW

**Comment by krishvoor** [comment]
Hi @eloycoto -

This PR would need you to following variables in TravisCI -
* DOCKERHUB_TOKEN
* DOCKERUSER
* QUAY_ID
* QUAY_TOKEN

Please help review ^^^

**Review by eloycoto — APPROVED** [review]

**Comment by krishvoor** [comment]
Can you help, get this merged?

**Comment by mganisin** [comment]
Nicely done @krishvoor. I like the Makefile which makes it indenpendent of CI tool. Anyway... :-)

1) Would you mind to rewrite it for github actions?
2) If done as github action it might be handy to utilize actions prepared by docker to build multiarch as it is here for example:  https://github.com/3scale-qe/mockserver-container/blob/main/.github/workflows/release.yaml Contrary to Makefile it creates dependency on github, however the recipe is pretty simple and easy to read and if necessary one day it will be still easy to rewrite it to something else.
What do you think?

Last but not least the question is whether Eloy's docker is now correct place to publish the image as this now belongs to shared project on github.

**Comment by eloycoto** [comment]
> Last but not least the question is whether Eloy's docker is now correct place to publish the image as this now belongs to shared project on github.

:sweat_smile:  I'm ok to store in that, but yeah, 3scale has a Quay repo to be used.

**Comment by krishvoor** [comment]
Hey @mganisin, @eloycoto 👋,

Sure, can restructure this to work with GitHub Actions. From long term solutions, it would be nice to stage them to 3scale's quay

**Comment by mganisin** [comment]
Hi @krishvoor I created PR https://github.com/3scale-qe/tinyproxy/pull/2 where:
 - the image is based on alpine (that is a must actually, amazing results)
 - github action is created to build it for amd64, ppc64le & s390x and to publish it on ghcr.io/3scale-qe/tinyproxy
 - I think ghcr.io/3scale-qe/tinyproxy is great option for transitional period (before we find/decide what's final place)
Have a look and let me know. Thanks!

**Comment by krishvoor** [comment]
Hi @mganisin, thanks for the quick-fix #2
Not sure how much of GHA credits we would need in the long term.
GHA is a bit more "slow" when working w/ multi-architecture(s). However, since this is going to be a one-time effort we can definitely work with this approach.

**Pull request merged**
